apiVersion: v1
kind: Pod
metadata:
  labels:
    label: kaniko-builder
    name: kaniko-builder
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:latest
    # El JNLP necesita el workspace para reportar el estado al master
    volumeMounts:
    - name: workspace-volume
      mountPath: /home/jenkins/workspace 
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command: ["cat"]
    tty: true
    volumeMounts:
    - name: workspace-volume
      mountPath: /home/jenkins/workspace
    - name: docker-config
      mountPath: /kaniko/.docker
  volumes:
  - name: workspace-volume
    emptyDir: {}
  - name: docker-config
    secret:
      secretName: docker-hub-creds
      items:
      - key: .dockerconfigjson
        path: config.json