pipeline {
    agent { label 'agent-builder' }
    parameters {
        string(name: 'APP_NAME', defaultValue: '<APP_NAME>', description: 'Nombre de la APlicacion')
        string(name: 'VERSION' , defaultValue: '<VERSION>', description: 'Version de la imagen')
        string(name: 'BRANCH', defaultValue: 'master', description: 'Branch')
    }

    environment{
        REG = "docker.io/pabloxr12/pxr207-"
        BRANCH_NAME = "${params.BRANCH}"

    }

    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM', 
                    branches: [[name: "${env.BRANCH_NAME}"]], // O la rama que necesites
                    userRemoteConfigs: [[
                        url: "https://github.com/priera12/PXR_K8S.git"
                        credentialsId: 'Jenkins-pipeline' // El ID de tu credencial
                    ]]
                ])
            }
        }
        stage('Deploy to Minikube') {
            steps {
                script {
                    def IMAGE = "${env.REG}${params.APP_NAME}:${params.VERSION}"
                        withCredentials([file(credentialsId: 'multinode-demo-certificates', variable: 'KUBECONFIG')]) {
                            dir("Helm/${params.APP_NAME}"){
                                script {
                                    // Helm detecta automáticamente la variable de entorno KUBECONFIG
                                    sh "helm upgrade ${params.APP_NAME} ./${params.APP_NAME} --namespace ${params.APP_NAME} --set image.repository=${IMAGE} --reuse-values"
                                    }
                            }
                        }
                }
            }
        }
    }
}