pipeline {
    agent { label 'agent-deployer' }
    parameters {
        string(name: 'APP_NAME', defaultValue: '<APP_NAME>', description: 'Nombre de la APlicacion')
        string(name: 'VERSION' , defaultValue: '<VERSION>', description: 'Version de la imagen')
        string(name: 'BRANCH', defaultValue: 'master', description: 'Branch')
    }

    environment{
        REG = "pabloxr12/pxr207-"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM', 
                    branches: [[name: "${params.BRANCH}"]], // O la rama que necesites
                    userRemoteConfigs: [[
                        url: "https://github.com/priera12/PXR_K8S.git",
                        credentialsId: 'Jenkins-pipeline' // El ID de tu credencial
                    ]]
                ])
            }
        }
        stage('Deploy to Minikube') {
            steps {
                script {
                    container('helm'){
                        def IMAGE = "${env.REG}${params.APP_NAME}:${params.VERSION}"
                            withCredentials([file(credentialsId: 'kubeconfig-file-type', variable: 'KUBECONFIG')]) {
                                dir("Helm/${params.APP_NAME}"){
                                    script {
                                        def APP = params.APP_NAME.replaceAll('_', '-')
                                        // Helm detecta automáticamente la variable de entorno KUBECONFIG
                                        sh "helm upgrade --install ${APP} . --set image.repository=${IMAGE} --reuse-values"
                                        }
                                }
                            }
                    }
                }
            }
        }
    }
}